Repository finos/common-cloud-controls, pull requests merged in 2024-07, with the labels that each got.

#244 Added primer
  FINOS CCC Primer June 2024.pdf
  Readme.md
Labels: communications

#223 Creation of Global Markdown Formatting and Linting GitHub Actions
  .config/.markdownlint.yaml
  .config/.prettierrc
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/minutes_all-hands-comms.md
  .github/ISSUE_TEMPLATE/minutes_community-structure.md
  .github/ISSUE_TEMPLATE/minutes_delivery.md
  .github/ISSUE_TEMPLATE/minutes_duplication-reduction.md
  .github/ISSUE_TEMPLATE/minutes_security.md
  .github/ISSUE_TEMPLATE/minutes_taxonomy.md
  .github/ISSUE_TEMPLATE/support_question.md
  .github/workflows/format-check.yml
  .github/workflows/linting-check.yml
  .github/workflows/pr_workflow.yaml
  .gitignore
  Governance.md
  Notices.md
  Readme.md
  Scope.md
  docs/formation/bootstrap.md
  docs/governance/community-groups.md
  docs/governance/community-guidelines/README.md
  docs/governance/community-guidelines/communication.md
  docs/governance/community-guidelines/content-standards-and-practices/README.md
  docs/governance/community-guidelines/content-standards-and-practices/markdown/formatting-guidelines.md
  docs/governance/community-guidelines/content-standards-and-practices/markdown/linting-guidelines.md
  docs/governance/community-guidelines/meetings.md
  docs/governance/community-guidelines/member-roles.md
  docs/governance/community-guidelines/proposing-working-group.md
  docs/governance/community-guidelines/templates/charter.md
  docs/governance/community-policies/README.md
  docs/governance/finos-poc.md
  docs/governance/steering/charter.md
  docs/governance/steering/elections.md
  docs/governance/working-groups/communications/charter.md
  docs/governance/working-groups/community-structure/charter.md
  docs/governance/working-groups/delivery/charter.md
  docs/governance/working-groups/duplication-reduction/charter.md
  docs/governance/working-groups/security/charter.md
  docs/governance/working-groups/taxonomy/charter.md
  docs/training/Readme.md
  docs/training/lint_format_user_guide.md
  docs/training/oscal/examples/Readme.md
  docs/training/oscal/oscal.md
  participants.md
  services/common-cloud-services.md
  services/compute-services.md
  services/compute/virtual-machines/taxonomy.md
  services/database-services.md
  services/database/relational/taxonomy.md
  services/networking-services.md
  services/networking/loadbalancer/taxonomy.md
  services/storage-services.md
  services/storage/object/controls.md
  services/storage/object/taxonomy.md
  services/storage/object/threats.md
Labels: delivery

#222 Create Resource Overview and Approach.md
  docs/resources/frameworks/MITRE ATT&CK.md
  docs/resources/readme.md
Labels: duplication reduction
