Repository finos/common-cloud-controls, pull requests merged in 2024-11, with the labels that each got.

#509 Create features.yaml for SecMgmt
  services/crypto/secMgmt/features.yaml
Labels: taxonomy

#543 #534: Add yaml linter
  .config/.markdownlint.yaml
  .config/.yamllint
  .github/workflows/format-check.yml
  .github/workflows/links.yml
  .github/workflows/linting-check.yml
  .github/workflows/pull_request.yaml
  .github/workflows/release.yml
  .github/workflows/sonatype_scan.yaml
  .github/workflows/stale.yml
  .github/workflows/stale_meeting.yml
  .github/workflows/todo-check.yml
  .github/workflows/yaml-check.yml
  .gitvote.yml
  docs/resources/templates/controls.yaml
  docs/resources/templates/metadata.yaml
  docs/resources/templates/threats.yaml
  docs/resources/training/oscal/examples/catalog/yaml/OSCAL_CCC_Catalog_option1.yaml
  docs/resources/training/oscal/examples/catalog/yaml/OSCAL_CCC_Catalog_option2.yaml
  services/ai-ml/gen-ai/features.yaml
  services/ai-ml/gen-ai/metadata.yaml
  services/ai-ml/mlde/controls.yaml
  services/ai-ml/service-families.yaml
  services/app-integration/message/controls.yaml
  services/app-integration/message/threats.yaml
  services/app-integration/service-categories.yaml
  services/common-controls.yaml
  services/common-features.yaml
  services/common-threats.yaml
  services/compute/serverless-computing/controls.yaml
  services/compute/serverless-computing/threats.yaml
  services/compute/service-categories.yaml
  services/compute/virtual-machines/features.yaml
  services/crypto/key/controls.yaml
  services/crypto/key/features.yaml
  services/crypto/key/threats.yaml
  services/crypto/secMgmt/features.yaml
  services/crypto/service-families.yaml
  services/database/relational/metadata.yaml
  services/database/relational/threats.yaml
  services/database/service-categories.yaml
  services/database/warehouse/controls.yaml
  services/database/warehouse/threats.yaml
  services/networking/vpc/controls.yaml
  services/networking/vpc/features.yaml
  services/networking/vpc/threats.yaml
  services/service-families.yaml
  services/storage/object/controls.yaml
  services/storage/object/metadata.yaml
  services/storage/object/threats.yaml
  services/storage/service-categories.yaml
Labels: community structure

#560 Disallow PRs to be merged with broken links
  .github/workflows/links.yml
  docs/governance/community-guidelines/releases/cmb/README.md
Labels: community structure

#519 Detailed secret management features
  services/crypto/secMgmt/features.yaml
  services/crypto/secrets/features.yaml
  services/crypto/secrets/metadata.yaml
Labels: taxonomy

#565 db backup restore threat
  services/database/relational/threats.yaml
Labels: security, threat definitions
