Repository finos/common-cloud-controls, pull requests merged in 2025-01, with the labels that each got.

#549 Create features.yaml for compute/batchproc
  services/compute/batchproc/features.yaml
Labels: taxonomy

#472 Re-worked features.yaml for AIML/MLDE
  services/ai-ml/mlde/features.yaml
Labels: taxonomy

#504 Updated features.yaml for Database/warehouse
  services/database/warehouse/features.yaml
Labels: taxonomy

#595 Detailed Container Registry Features
  services/devtools/container-registry/controls.yaml
  services/devtools/container-registry/features.yaml
  services/devtools/container-registry/metadata.yaml
  services/devtools/containerReg/features.yaml
  services/devtools/service-categories.yaml
Labels: pending approval

#604 Detailed batch processing and build features
  services/compute/batchproc/features.yaml
  services/compute/batchproc/metadata.yml
  services/compute/service-categories.yaml
  services/devtools/build/features.yaml
  services/devtools/build/metadata.yaml
  services/devtools/build/threats.yaml
  services/devtools/service-categories.yaml
Labels: pending approval

#608 Detailed MLDE and Data warehouse features
  services/ai-ml/mlde/features.yaml
  services/ai-ml/mlde/metadata.yaml
  services/ai-ml/service-families.yaml
  services/database/warehouse/features.yaml
  services/database/warehouse/metadata.yaml
Labels: pending approval

#510 Create threats.yaml for SecMgmt
  services/crypto/SecMgmt/threats.yaml
Labels: security, threat definitions

#508 Create controls.yaml for secMgmt
  services/crypto/secMgmt.yaml
Labels: security, control definitions

#594 Controls work
  services/database/relational/controls.yaml
  services/database/relational/threats.yaml
Labels: stale

#647 change(docs): Object Storage Release Fixes
  services/storage/object/controls.yaml
Labels: delivery
